ports:
- port: 8080
checkoutLocation: lama
workspaceLocation: lama
tasks:
- command: |
    cd .. &&
    curl -OL https://github.com/goreleaser/goreleaser/releases/download/v0.108.0/goreleaser_Linux_x86_64.tar.gz &&
    tar xfz goreleaser_Linux_x86_64.tar.gz &&
    rm goreleaser_Linux_x86_64.tar.gz &&
    cd lama
